/*
 *  main.c
 *	part of talculator
 *  	(c) 2002-2014 Simon Flöry (simon.floery@rechenraum.com)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
 
/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include "calc_basic.h"
#include "talculator.h"
#include "config_file.h"
#include "general_functions.h"
#include "ui.h"

/* i18n */

#include <libintl.h>
#define _(String) gettext (String)
#define gettext_noop(String) String
#define N_(String) gettext_noop (String)

#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <glib.h>
#include <glib/gstdio.h>

#define MASK_NUMLOCK GDK_MOD2_MASK

s_preferences		prefs;
s_constant 			*constant;
s_user_function		*user_function;
talc_engine		*calc_engine = NULL;
s_tab_context		default_tab_context = {
	.tab_current_status = {0, 0, 0, 0, FALSE, FALSE, TRUE},
	.tab_mode = BASIC_MODE,
	.tab_vis_number = TRUE,
	.tab_vis_angle = TRUE,
	.tab_vis_notation = TRUE,
	.tab_vis_funcs = TRUE,
	.tab_vis_logic = TRUE,
	.tab_vis_dispctrl = TRUE,
	.tab_vis_standard = TRUE,
	.tab_def_number = CS_DEC,
	.tab_def_angle = CS_RAD,
	.tab_memory = {NULL, 0},
	.tab_display_view = NULL,
	.tab_display_buffer = NULL,
	.tab_display_result_counter = 0,
	.tab_display_result_line = 0,
	.tab_display_last_arith = ' ',
	.tab_display_brackets = 0,
	.tab_view_xml = NULL,
	.tab_button_box_xml = NULL,
	.tab_dispctrl_xml = NULL,
	.tab_classic_view_xml = NULL,
	.tab_paper_view_xml = NULL,
	.tab_rpn_stack = NULL,
	.tab_rpn_stack_len = 0
};
s_tab_context		*active_tab = &default_tab_context;

void print_usage ()
{
    printf (_("\n%s v%s, (c) 2002-2014 Simon Flöry\n\n\
Usage: %s [options]\n\n\
options:\n\
(GTK options)\n\
 -h, --help\t\tShow this usage message\n\
 -v, --version\t\tShow version information\n\n\
Compiled against GTK version %i.%i.%i\n\
Linked against GTK version %i.%i.%i\n\
Evaluation engine: libqalculate.\n"),
	PACKAGE, VERSION, PACKAGE,
	GTK_MAJOR_VERSION, GTK_MINOR_VERSION, GTK_MICRO_VERSION,
	gtk_major_version, gtk_minor_version, gtk_micro_version
	);
}

/* see GtkWidget can-activate-accel signal */

/*
 * main
 */

#ifdef WITH_HILDON
/* Registering the hildon application */
static GtkWidget* glade_hildon_window_new (GtkBuilder *xml, GType type, GladeWidgetInfo *info)
{
    return hildon_window_new();
}
#endif

int main (int argc, char *argv[])
{
    char		*config_file_name;
	GtkWidget 	*main_window;

#ifdef WITH_HILDON
	HildonProgram   *hildon_program;
#endif
	
	/*
	 * gtk_init runs (among other things) setlocale (LC_ALL, ""). Therefore we
	 * have to/can deal with i18n only from this point.
	 * call gtk_init before getopts to get gtk options stripped (--display etc)
	 */

	gtk_init (&argc, &argv);
	
	bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (PACKAGE, "UTF-8");
	textdomain (PACKAGE);
    	
	if (argc > 1) {
		print_usage ();
		return EXIT_SUCCESS;
	}

	if (!talc_engine_available ()) {
		fprintf (stderr, _("[%s] libqalculate backend unavailable; exiting.\n"), PACKAGE);
		return EXIT_FAILURE;
	}
	calc_engine = talc_engine_new ();
	
    /* get config file. 
     * 
     * at first we check if there is env variable GALCULATOR_CONFIG set. If not,
     * we try the XDG location with g_get_user_config_dir. If this does not 
     * succeed, we try the old non-spec location, that will be migrated to the
     * XDG location.
     */
    config_file_name = getenv("GALCULATOR_CONFIG");
    if (config_file_name) config_file_name = g_strdup(config_file_name);
    else {
		/* if there is a config file in g_get_user_config_dir, use that. 
		 * otherwise, try old method. anyway, we will store in 
		 * g_get_user_config_dir and tell the user to remove the file from the
		 * old location.
		 */
		config_file_name = g_strdup_printf("%s/%s/%s", g_get_user_config_dir(), PACKAGE, CONFIG_FILE_NAME);
		if (!g_file_test(config_file_name, G_FILE_TEST_IS_REGULAR)) {
			/* create directory for new config file location */
			char *path = g_strdup_printf("%s/%s", g_get_user_config_dir(), PACKAGE);
			if (g_mkdir(path, 0755) == -1 && errno != EEXIST) 
				fprintf (stderr, _("[%s] configuration file: Failed to create directory %s.\n"), PACKAGE, path);
			g_free(path);
			/* check old file location */
			char *config_file_name_old = g_strdup_printf("%s/%s", g_get_home_dir(), CONFIG_FILE_NAME_OLD);
			if (g_file_test(config_file_name_old, G_FILE_TEST_IS_REGULAR)) {
				fprintf (stderr, _("[%s] configuration file: We will move the configuration \
file from %s to %s. After you quit %s, you may remove the configuration file from its old location %s.\n"), 
PACKAGE, config_file_name_old, config_file_name, PACKAGE, config_file_name_old);
				g_free(config_file_name);
				config_file_name = config_file_name_old;
			} else g_free(config_file_name_old);
		}
	}

	prefs = config_file_read (config_file_name);
	constant = config_file_get_constants();
    user_function = config_file_get_user_functions();

	current_status.notation = prefs.def_notation;

#ifdef WITH_HILDON
	glade_register_widget (HILDON_TYPE_WINDOW, glade_hildon_window_new, glade_standard_build_children, NULL);
	hildon_program = HILDON_PROGRAM(hildon_program_get_instance());
#endif

	/* at first get the main frame */
	
	/* sth like ui_launch_up_ui for splitting into first time wizard? */
	main_window = ui_main_window_create();
#ifdef WITH_HILDON
	hildon_program_add_window(hildon_program, HILDON_WINDOW(main_window));
	g_set_application_name("Galculator");
	create_hildon_menu(HILDON_WINDOW(main_window));
#endif	
	gtk_window_set_title ((GtkWindow *)main_window, PACKAGE);

	/* usually, only Shift, CTRL and ALT modifiers are paid attention to by 
	 * accelerator code. add MOD2 (NUMLOCK allover the world?) to the list. 
	 * We have to do this for a working keypad.
	 */

	gtk_accelerator_set_default_mod_mask (gtk_accelerator_get_default_mod_mask () | GDK_MOD2_MASK); 
				  
	/* prepare RPN runtime */
	rpn_init (prefs.stack_size, 0);
		
	/* apply changes */
	apply_preferences (prefs);
    remember_display_values ();

	memory.data = NULL;
	memory.len = 0;

    /* make the window as small as possible */
	gtk_window_resize ((GtkWindow *)main_window, 1, 1);

	/* gtk_widget_show main window as late as possible */
	gtk_widget_show (main_window);
	
	/*
	 * enter GTK's main loop
	 */
	
	gtk_main ();

	/* 
	 * save changes to configuration file 
	 */

	if (!getenv("GALCULATOR_CONFIG")) {
		/* If the config file name is not from an env variable, enforce the
		 * new location.
		 */
		g_free(config_file_name);
		config_file_name = g_strdup_printf ("%s/%s/%s", g_get_user_config_dir(), PACKAGE, CONFIG_FILE_NAME);
	}
	config_file_write (config_file_name, prefs, constant, user_function);
	g_free (config_file_name);

	return EXIT_SUCCESS;
}
